### ISSUE TITLE
No type definitions

### ISSUE THREAD

**Issue by joelpierre** [TheBeyondGroup/shopify-rich-text-renderer#29]
Any change you can add a simple type declaration file to this pkg? Appreciate it is very simple but my TS project is complaining a lot... 😅

**Comment by jeffreyguenther** [comment]
Great idea! If you want to open a PR, we'll review it. Otherwise, we'll add them in the next while.

**Comment by JCDriessen** [comment]
I also stumbled on this a few days ago, and I would like to remove `declare module '@thebeyondgroup/shopify-rich-text-renderer';` from my typings.d.ts in my project :P, so I tried adding them myself in this pull request: https://github.com/TheBeyondGroup/shopify-rich-text-renderer/pull/30

**Comment by mcqua007** [comment]
@JCDriessen @joelpierre I just wanted to let you know that we added the type defs (Thanks @JCDriessen ) to in the latest release [v2.0.2](https://github.com/TheBeyondGroup/shopify-rich-text-renderer/releases/tag/v2.0.2)

**Comment by joelpierre** [comment]
@JCDriessen @mcqua007  thanks guys 🙌🏽

**Comment by JCDriessen** [comment]
@mcqua007 While testing the new version of the package I stumpled upon something we forgot :p:
The index.d.ts file does not get published with the package.

I have no experience with rollup (only ng-packagr), but i feel like this needs to be added/changed to the package.json under files:
`"index.d.ts"`

**Comment by joelpierre** [comment]
@JCDriessen you just need to say where the types are in your package.json. I can raise a PR for that

**Comment by JCDriessen** [comment]
@joelpierre 
That is allready in the package.json: `typings": "index.d.ts",` in [package.json](https://github.com/TheBeyondGroup/shopify-rich-text-renderer/blob/main/package.json).

The problem is that the typings file (`index.d.ts`) is not published to npm with the package.

**Comment by joelpierre** [comment]
ahh sorry I didn't check before commenting but yeah you should just be able to add it to files, https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files as you are using files in package.json npm will honour that only. 

Personally I think its best to copy the index.d.ts into your dist folder so it's cleaner maybe do this after the build command is fired e.d `npx rollup -c && cp index.d.ts dist/index.d.ts`

and update the package json with the reference. You could also use the exports fields in package json too. I think thats the "newer" approach.

**Comment by joelpierre** [comment]
Let me know your thoughts on this https://github.com/TheBeyondGroup/shopify-rich-text-renderer/pull/32

**Comment by joelpierre** [comment]
Or you could just do this I believe https://github.com/TheBeyondGroup/shopify-rich-text-renderer/pull/33

**Comment by JCDriessen** [comment]
I would strongly suggest https://github.com/TheBeyondGroup/shopify-rich-text-renderer/pull/33, becuase copying files manually (in a command but still) is very OS dependend, Windows users need xcopy instead of cp and use \\ instead of / for paths (inside npm commands).

I feel like it is cleaner to let the packager (rollup in this case) manage it.

**Comment by mcqua007** [comment]
@JCDriessen @joelpierre I think #33 makes the most sense. This will just allow the type defs to be published to npm in the root of the package. This is something that was overlooked in @JCDriessen PR.

**Comment by mcqua007** [comment]
@joelpierre @JCDriessen Ok, I just merged the change and published to npm ([v.2.0.3](https://github.com/TheBeyondGroup/shopify-rich-text-renderer/releases/tag/v2.0.3)).

**Comment by JCDriessen** [comment]
Thanks @mcqua007! I just implemented this and works perfectly.
